name: Release Electron Windows (by tag)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, ia32]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Prepare publish/sign env
        shell: pwsh
        run: |
          $token = "${{ secrets.GH_TOKEN }}"
          if (-not $token -or $token -eq '') { $token = "${{ secrets.GITHUB_TOKEN }}" }
          "GH_TOKEN=$token" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

          if (-not [string]::IsNullOrEmpty("${{ secrets.CSC_LINK }}")) {
            "CSC_LINK=${{ secrets.CSC_LINK }}" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          }
          if (-not [string]::IsNullOrEmpty("${{ secrets.CSC_KEY_PASSWORD }}")) {
            "CSC_KEY_PASSWORD=${{ secrets.CSC_KEY_PASSWORD }}" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          }

      - name: Build & publish release
        run: npx electron-builder --win --${{ matrix.arch }} --publish always

